### ISSUE TITLE
Unable to open issuehunter.co

### ISSUE THREAD

**Issue by DevDengChao** [issuehunter/issuehunter#31]
![TIM截图20190918155624](https://user-images.githubusercontent.com/16363180/65128910-e82a1900-da2c-11e9-8eb9-93746cb07828.png)

![image](https://user-images.githubusercontent.com/16363180/65129099-3dfec100-da2d-11e9-9856-685479e6048c.png)

I cannot open http://issuehunter.co but I found https://issuehunt.io from another issue https://github.com/issuehunter/issuehunter/issues/30 .

**Comment by hexagonrecursion** [comment]
Looks like a dead github org - no new commits since 2018. https://issuehunt.io/ seams to be completely unrelated.
